### PR TITLE
Finished the core_nl-nl

### PR DESCRIPTION
**Pull request by Audition-CSBlock**

### CODE REVIEW

**Comment by TiEul** [comment]
Thanks!

**Comment by timEulitz** [comment]
There is am missing comma in line 37 of the core translation file but I fixed it, don't worry about that!

**Comment by TiEul** [comment]
There is am missing comma in line 37 of the core translation file but I fixed it, don't worry about that!

**Comment by Audition-CSBlock** [comment]
@TiEul oops sorry, didn't notice it :sweat_smile:

_Sent from my OnePlus 6 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Audition-CSBlock** [comment]
Oops sorry, didn't notice that :sweat_smile:

**Comment by Audition-CSBlock** [comment]
And btw, when is this going to be pushed to a new version?

**Comment by TiEul** [comment]
Hey, it will be pushed with the next release, you can always use the Wallpaper Engine Beta to look at the translations a little early. We do not have any specific release dates for updates, they're released "when they are ready", but it usually only takes a month or so between updates.

**Pull request merged**
