### PR TITLE
Update ui_ru-ru.json

### PR DESCRIPTION
**Pull request by MagVI**
Not sure about tags, mb ill edit it when I see it live (since "ui_workshop_tags_wallpaper" and next)

### CODE REVIEW

**Comment by TiEul** [comment]
Hey! You can already see them in the beta, we wrote about it on the forums. I can also provide screenshots if that helps:

https://steamcommunity.com/app/431960/discussions/2/2261313417709293714/

About your translation: Can you check if your translation of "assets" is really appropriate? It looks like you translated it as "Packages" though it should be more in the direction of "resources". Like "resources to create wallpapers". It's about sharing new effects / materials that people can use in the editor.

**Comment by MagVI** [comment]
ok, let me check

**Comment by MagVI** [comment]
sry, my bad, fixed

**Comment by MagVI** [comment]
about tags I mean when I see them translated ill edit them if they are wrong

**Comment by TiEul** [comment]
Thanks! I will make sure the next beta update will contain your latest translations and you can have a look once that is live. They are all in the new asset browser in the editor, not in the wallpaper browser.

**Comment by MagVI** [comment]
ok, ty!

**Pull request merged**
