### PR TITLE
Update ui_id-id.json

### PR DESCRIPTION
**Pull request by Anfia**
Hi, it's me Anfia from Steam.

I check the github that the strings is being updated again eh?

Since the wallpaper engine is not yet getting newest stable update (assume it's still on beta build), I try commit pull requesttranslation directly on the github (maybe at the next time, directly to github.

Btw, there's only 1 revision on 1 line at "ui_settings_about_faq". I put it inside same commit request.

cheers~ :)

### CODE REVIEW

**Comment by TiEul** [comment]
Thanks, I have added the new strings! And yeah, these are only on the beta for now but we will likely release an update by the end of this week, you should find these strings in the app and your name in the "About" tab!

**Comment by Anfia** [comment]
Thank you.
Oh right, if I ask for.. I want to be a contributor for translating Wallpaper Engine, like Mr. Naufal & Mr. Papin Faizal, so I can update the translation more faster without waiting.

I already contact Mr.Papin for continue contribute and he approve it.

**Comment by TiEul** [comment]
Hey, there is no official contributor list or something like that. If you'd like to submit changes to translations, the best way is to make pull requests to this repository and we'll review and merge them. In the future we may switch to a different system but we need more time to prepare that.

**Comment by Anfia** [comment]
ohh.. okay okay. I think there's contributor.. but I guess that must be pull request directly to 'locale' folder instead missing translation..

all right. thank you for the info. Glad I can continue the translation :'))

**Comment by Anfia** [comment]
Also, I try checking the beta build, and it's seems the translation is clear and neat tho (before this commit update).

Although.. on the "About" tab, there's no my name...

**Comment by TiEul** [comment]
Hey, yeah, we have not pushed these changes to the beta yet but they'll be there with the next update (which may already be the final release, we'll see).

> ohh.. okay okay. I think there's contributor.. but I guess that must be pull request directly to 'locale' folder instead missing translation..

Yeah, that's the way to go!

**Pull request merged**
