### PR TITLE
Proof reading, bit wording revision & update ui_id-ID.json

### PR DESCRIPTION
**Pull request by Anfia**

### CODE REVIEW

**Comment by timEulitz** [comment]
Hey, sorry but you have added a lot of HTML to strings where it does not belong, I am afraid have had to revert this change completely. Please do not modify or add any HTML or placeholder brackets, it will invalidate the translation file and not pass the release validation.

**Comment by TiEul** [comment]
Hey, sorry but you have added a lot of HTML to strings where it does not belong, I am afraid have had to revert this change completely. Please do not modify or add any HTML or placeholder brackets, it will invalidate the translation file and not pass the release validation.

**Comment by Anfia** [comment]
oh, then it's should be fill the missing translation first then when missing translation submit applied, then editing on locale folder? all right, I'll try it. Thanks for reading my thread on steam btw.

**Comment by Anfia** [comment]
oh, sorry about that, seems there's misplacing the code when I'm managing it from other tab browsers. all right, I'll try fix it. Thanks for reading my thread on steam btw.

**Pull request merged**
