### PR TITLE
Added missing translations (fixed)

### PR DESCRIPTION
**Pull request by MrKingMichael**

### CODE REVIEW

**Comment by TiEul** [comment]
Thanks!

**Comment by timEulitz** [comment]
Errrm, actually you edited the English file :see_no_evil:. I will have to revert this.

**Comment by timEulitz** [comment]
Please just commit your changes to this file directly:

https://github.com/Wallpaper-Engine-Team/wallpaper-engine-translations/blob/master/missing_translations/core_el-gr.json

I will take care of the rest, it's less error-prone that way.

**Comment by TiEul** [comment]
Since you accidentally pushed everything into the English file and I merged, I had to revert it again, so it's completely undone now.

Please just commit your changes to this file directly: 

https://github.com/Wallpaper-Engine-Team/wallpaper-engine-translations/blob/master/missing_translations/core_el-gr.json

I will take care of the rest, it's less error-prone that way because we have scripts that merge the files properly.

**Comment by MrKingMichael** [comment]
Oh, boy! I'm terribly sorry for that. I'm beyond stupid. I keep making foolish mistakes like this. A million apologies about this! I will do it right this time.

**Pull request merged**
