### PR TITLE
Update ui_zh-chs.json

### PR DESCRIPTION
**Pull request by HaoJun0823**
I think most are fine :)
It's better to let professionals polish it.

### CODE REVIEW

**Comment by TiEul** [comment]
Hey dude! Thanks a lot! Can you quickly check this for me:

In the past, someone said the word "asset" should not be translated into "资产" but rather "资源" because "资产" means "assets" as in "monetary assets" while "资源" means "assets" as in resources (wallpaper resources / wallpaper assets). Is that correct? I can also search and re-place all "资产" or does that break the grammar? The same would be for zh-cht I assume. I speak absolutely zero Chinese aside from "ni hao, wo laizi deguo" so I have absolutely no idea what would be better.

**Comment by HaoJun0823** [comment]
> 
> 
> Hey dude! Thanks a lot! Can you quickly check this for me:
> 
> In the past, someone said the word "asset" should not be translated into "资产" but rather "资源" because "资产" means "assets" as in "monetary assets" while "资源" means "assets" as in resources (wallpaper resources / wallpaper assets). Is that correct? I can also search and re-place all "资产" or does that break the grammar? The same would be for zh-cht I assume. I speak absolutely zero Chinese aside from "ni hao, wo laizi deguo" so I have absolutely no idea what would be better.

Sorry man, I found it a little late.
Asset, Resource, and Content can all be translated as "资源" in Chinese. In fact, I don't know how to translate, but in English these three words have various small differences.
Because the word is indeed a bit tricky, I translated it into "资产" according to the habits of the productivity editor, which is why I want someone to polish it.
So, if you want to change to "资源", I will go and modify it.

**Comment by TiEul** [comment]
Hey, don't worries, I really appreciate your help! Like I said, I don't speak Chinese, it's just what someone told me and I cannot really judge it any further like that. I also had problems when creating the German translation for the word "assets" because it's really unique in English. I think it's best to imagine that the word is just "resources" like "wallpaper resources" or "wallpaper materials". If 资源 is more close to that, then I think it would be best to use this term from now on, the same for traditional Chinese. We also have this existing string which still uses "资产" which I would change for consistency's sake:

    "ui_editor_importer_compiling_assets_for": "正在编译资产",

Is this correct:

    "ui_editor_importer_compiling_assets_for": "正在编译资源",

If I can simply replace it like this, it would be an easy search and replace but you can do it as well if it needs some grammatical adaptions!

**Comment by HaoJun0823** [comment]
> 
> 
> Hey, don't worries, I really appreciate your help! Like I said, I don't speak Chinese, it's just what someone told me and I cannot really judge it any further like that. I also had problems when creating the German translation for the word "assets" because it's really unique in English. I think it's best to imagine that the word is just "resources" like "wallpaper resources" or "wallpaper materials". If 资源 is more close to that, then I think it would be best to use this term from now on, the same for traditional Chinese. We also have this existing string which still uses "资产" which I would change for consistency's sake:
> 
> ```
> "ui_editor_importer_compiling_assets_for": "正在编译资产",
> ```
> 
> Is this correct:
> 
> ```
> "ui_editor_importer_compiling_assets_for": "正在编译资源",
> ```
> 
> If I can simply replace it like this, it would be an easy search and replace but you can do it as well if it needs some grammatical adaptions!

I finished the replacement, and there were not too many problems, all the "资产" were replaced by "资源".

**Comment by TiEul** [comment]
Thanks a lot!

**Pull request merged**
