### PR TITLE
Update ui_it-it.json

### PR DESCRIPTION
**Pull request by Giaskoz**
Tried to translate all the remaining strings.

### CODE REVIEW

**Comment by TiEul** [comment]
Thanks a lot!

**Comment by Giaskoz** [comment]
If my name makes it to the community translators list could you please write Giasko instead of Giaskoz? It's my original name but when I created my account on GitHub it was already used. Thanks.

**Comment by TiEul** [comment]
Will do!

**Comment by Giaskoz** [comment]
Appreciate it. Regards.

**Pull request merged**
