### PR TITLE
Update core_de-de.json

### PR DESCRIPTION
**Pull request by JanDevDE**
Removed additional symbol

### CODE REVIEW

**Comment by Biohazard90** [comment]
Does it show up twice in the context menu for you?

I put the ampersand in there twice because Windows will remove one when it actually displays the text. This isn't the correct solution I think, so if you actually see two ampersands I'll have to look into solving the issue differently.

**Comment by JanDevDE** [comment]
Yep, they did show up twice.

**Comment by Biohazard90** [comment]
Bummer. Which version of Windows are you using? It's set to German I presume?

Is any special theme selected or installed perhaps?

Just using one removes it completely on my systems, maybe I should just not use any ampersands to avoid the issue.

**Comment by JanDevDE** [comment]
Nope. I use Windows 10 Home in English. No special theme selected.

**Comment by Biohazard90** [comment]
Thanks for the infos. I'm guessing that the menu has keyboard shortcuts (mnemonics?) disabled on your PC, causing Windows to not parse the ampersand. But even Microsoft doesn't consider this: https://support.microsoft.com/en-us/help/261320/how-to-use-an-ampersand-in-a-form-name,-menu,-or-control

I guess the only way to make it consistent is to either force parsing on or off for the menu somehow beforehand.

**Comment by TiEul** [comment]
Closing for inactivity.

**Pull request closed without merging**
